---
- name: Ensure docker service is enabled
  service:
    name: 'docker'
    enabled: True

- name: Create Docker upstart default config file
  template:
    src: 'docker-defaults.j2'
    dest: '/etc/default/docker'
  when: ansible_service_mgr == "upstart"
  notify:
    - Restart Docker

- name: Ensure docker systemd drop-in directory exists
  file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
  when: ansible_service_mgr == "systemd"

- name: Create Docker systemd drop-in file
  template:
    src: 'docker-systemd-service.j2'
    dest: '/etc/systemd/system/docker.service.d/override.conf'
  when: ansible_service_mgr == "systemd"
  register: dropinfile
  notify:
    - Restart Docker

- name: Reload systemd
  command: 'systemctl daemon-reload'
  when: ansible_service_mgr == "systemd" and dropinfile.changed