- name: Enable Docker yum repository | RedHat
  template:
    src: 'docker-repo.j2'
    dest: '/etc/yum.repos.d/docker.repo'
    owner: root
    group: root
    mode: 0644

- name: Import Docker GPG key | Redhat
  rpm_key:
    key: "{{ docker_yum_repo_gpg }}"
    state: present

- name: Ensure Docker Engine is installed | RedHat
  yum:
    name: 'docker-engine'
    state: present

- name: Ensure docker systemd drop-in directory exists
  file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory

- name: Create Docker systemd drop-in file
  template:
    src: 'docker-systemd-service.j2'
    dest: '/etc/systemd/system/docker.service.d/override.conf'
  register: dropinfile
  notify:
    - Restart Docker

- name: Reload systemd
  command: 'systemctl daemon-reload'
  when: dropinfile.changed == true