---
- hosts: all

  tasks:
    - name: Install required packages (Debian)
      package:
        name: '{{ item }}'
        state: present
      with_items:
        - gpg
      when: ansible_distribution == 'Debian'
